### ISSUE TITLE
Secondary column of ToC is not shown in latest reveal.js

### ISSUE THREAD

**Issue by figbux** [e-gor/Reveal.js-TOC-Progress#16]
Hello,

First off, thanks for the much needed plugin. But as the title says, I cannot get the sub-headers shown on the ToC.

![image](https://user-images.githubusercontent.com/22550594/105638083-e7579180-5e81-11eb-83d7-65a9cf419223.png)
 
My code is:

```html
         <div class="reveal">
             <div class="slides">
                 <section>
                     <section>
                         <h2>Slide 1</h2>
                     </section>
                     <section>
                         <h3>Slide 1.1</h3>
                     </section>
                 </section>
                 <section>
                     <section>
                         <h2>Slide 2</h2>
                     </section>
                     <section>
                         <h3>Slide 2.1</h3>
                     </section>
                 </section>
             </div>
         </div>

```

To see what I changed from the latest reveal.js, please see the comparison:
https://github.com/hakimel/reveal.js/compare/master...figbux:master 

Thanks for any help.

**Comment by e-gor** [comment]
That is happening because in your case the viewport (the element that gets the `data-state` in the `class` attribute when the slide is changed) is the `<body>` element, not the `<html>` element. I do not know if that is due to changes in reveal.js, due to some plugin, or something you changed.

Either case, this had been thought of, and you can fix the problem by calling initialize with a value of 'body' in the viewport parameter:
[`                                                        toc_progress.initialize(null,null,'body');`](https://github.com/figbux/reveal.js/blob/0dca684059095b370d43e944c750f36f5ecaa407/index.html#L55)

**Comment by figbux** [comment]
Great, worked, thanks!
