### ISSUE TITLE
3 columns on ToC progress?

### ISSUE THREAD

**Issue by figbux** [e-gor/Reveal.js-TOC-Progress#17]
Hello,
I have a question about this great plugin: Is there an easy way to get ToC depth level of 3? I try to structure my contents to have depht level of 2 but it's hard to do so. 
If it is not possible for now but if it's easy to code, you can consider this as a feature request.
Thanks!

**Comment by e-gor** [comment]
I guess it could be coded, but it's maybe more a question of space in the footer, 3 columns might be too much for some widths...

However, it is possible for you to have 3 levels (or 4, or more), or have 2 levels with many slides in each second level, and the plugin will show which second-level chapter you are in, even if that has many sub-levels or slides. I mean, each second level chapter does not have to be necessarily just one slide.

So adding the option of a third level is not in my plans, sorry. However, you are free to do it yourself. If you do it and it looks OK with 3 columns, and you make it optional (for example, with an optional parameter in the initialization) and it looks just as it does now in 2 columns, I would be ready to accept a PR and integrate it.

Tell me if you will try to do it, in order to leave the issue open or not, OK?

**Comment by figbux** [comment]
Thanks for your reply.
As I don't have enough experience with js, it'd take a long time for me to develop it. So we can close the issue now.

**Comment by e-gor** [comment]
> Thanks for your reply.
> As I don't have enough experience with js, it'd take a long time for me to develop it. So we can close the issue now.

Ok. At least I hope what I said is helpful and you can manage with it:

> However, it is possible for you to have 3 levels (or 4, or more), or have 2 levels with many slides in each second level, and the plugin will show which second-level chapter you are in, even if that has many sub-levels or slides. I mean, each second level chapter does not have to be necessarily just one slide.

**Comment by figbux** [comment]
> Ok. At least I hope what I said is helpful and you can manage with it:
> 
> > However, it is possible for you to have 3 levels (or 4, or more), or have 2 levels with many slides in each second level, and the plugin will show which second-level chapter you are in, even if that has many sub-levels or slides. I mean, each second level chapter does not have to be necessarily just one slide.

I'm sorry I'm a bit confused: So do you mean e.g if the head level is `h1` I can have subheaders `h2` and `h3`s; and `h1` will be in the first column whereas all `h2`, `h3` and `h4` etc will be shown on the right column?

```
h1 | h2
   | h3
   | h4
```

Or did you mean just `h2` will be on right and the rest will be hidden?:
```
h1 | h2
```

---

Actually I didn't use to know in reveal.js there are only 2 dimensions; I thought it could be like:
```
h1 -- h1 -- h1 -- h1
          |
         h2 -- h3
          |
         h2
```
But I see I can only have
```
h1 -- h1 -- h1 -- h1
          |
         h2
          |
         h3
          |
         h2
```

So now I think ToC progress' current behavior fits with revealjs' dimension policy.

**Comment by e-gor** [comment]
ToC progress will show in the first column the first `<h1>`, `<h2>` or `<h3>` found in a main `<section>`, that is, a section which is a direct child of `<div class="slides">`.

In the second column, it will show the first `<h1>`, `<h2>` or `<h3>` found in `<section>` elements that are children of main `<section>`s.

So what I meant is that you can have many slides that will show as being part of the same element in the second column, as long as they do not have a `<h1>`, `<h2>` or `<h3>` element (they can have `<h4>` or larger elements).

If you take a look at the [demo](https://e-gor.github.io/Reveal.js-TOC-Progress/demo/#/) (more exactly its [`index.html`](https://github.com/e-gor/Reveal.js-TOC-Progress/blob/master/demo/index.html) file), you will see a code like the following:

```
<div class="slides">
	<section id="main_section_1">
		<section id="slide_1" data-state="no-toc-progress">
			<h1 class="no-toc-progress">Reveal.js-TOC-Progress</h1>
			<h3>LaTeX Beamer-like progress indicator according to table of contents for Reveal.js HTML presentations</h3>
			<p>
				<small>Created by <a href="https://github.com/e-gor">Igor Leturia <em>e-gor</em></a> / <a href="http://twitter.com/ileturia">@ileturia</a> / <a href="http://eibar.org/blogak/e-gorblog">http://eibar.org/blogak/e-gorblog</a></small>
			</p>
		</section>
	</section>
	<section id="main_section_2">
		<section id="slide_2">
			<h2>Description</h2>
		</section>
		<section id="slide_3">
			<h3>What is Reveal.js-TOC-Progress?</h3>
			<p>Reveal.js-TOC-Progress is a plugin for the Reveal.js framework for HTML presentations (<a href="https://github.com/hakimel/reveal.js">https://github.com/hakimel/reveal.js</a>).</p>
		</section>
		<section id="slide_4">
			<h3>What does Reveal.js-TOC-Progress do?</h3>
			<p>Reveal.js-TOC-Progress includes a footer in all the slides of a Reveal.js presentation (with optional exclusion of some slides) that will show the progress in relation to the table of contents, in a similar way as in a LaTeX-Beamer presentation.</p>
		</section>
		<section id="slide_5">
			<h3>Example</h3>
			<p>You can see it working at the bottom of this slide and any other slide except the title.</p>
		</section>
		<section id="slide_6">
			<h3>Behaviour</h3>
			<p>The footer has two columns. The left column shows a list of the main sections (except those we explicitly tell to ignore), highlighting the section we are now in. The right column shows the subsections of the main section we are now in (again with the option of ignoring those we do not want to show), highlighting the subsection we are currently at.</p>
		</section>
		<section id="slide_7">
			<h3>Configurable options</h3>
			<p>The behaviour for too long section or subsection lists is configurable. The font of the text can be reduced to make the list fit in the footer, or the list will scroll when necessary.</p>
		</section>
		<section id="slide_8">
			<p>The background color of the footer is also configurable.</p>
		</section>
	</section>
	<section id="main_section_2">
		<section id="slide_9">
			<h2>Installation</h2>
		</section>
		<section id="slide_10">
			<h3>Necessary files</h3>
			<p>The <code>toc-progress</code> folder of the <code>plugin</code> folder has to be copied to the <code>plugin</code> folder of the Reveal.js presentation.</p>
		</section>
		<section id="slide_11">
			<h3>CSS</h3>
			<p>The CSS of the Reveal.js-TOC-Progress plugin is included dynamically when it is initialized. However, if we configure the presentation not to include the Reveal.js-TOC-Progress footer in the first page, this will be shown until the CSS is loaded dynamically, causing an ugly effect. To avoid it, include the CSS in the header of the Reveal.js presentation, with this line:</p>
			<pre><code><link rel="stylesheet" href="plugin/toc-progress/toc-progress.css"></code></pre>
		</section>
		<section id="slide_12">
			<h3>Plugin initialization</h3>
			<p>Include Reveal.js-TOC-Progress among the Reveal.js plugin initializations, like this:</p>
			<pre><code>...</code></pre>
		</section>
		<section id="slide_13">
			<h3>Customization</h3>
			<p>The <code>toc_progress.initialize</code> function can take two parameters:</p>
			<ul>
				<li><code>reducescroll</code>: if <code>'reduce'</code>, the font of the text of too long section or subsection lists is reduced to make the list fit in the footer; if <code>'scroll'</code> (default), the list will scroll when necessary.</li>
				<li><code>background</code>: a string of the form <code>'rgba(0,255,0,0.1)'</code>, for the background colour of the footer.</li>
			</ul>
		</section>
		<section id="slide_14">
			<p>Including the <code>toc_progress.create</code> function in the Reveal.js initialization is not compulsory. If it is not included, the key <code>q</code> has to be pressed to create the footer.</p>
		</section>
		<section id="slide_15">
			<p>For further customization (like making the footer a header, for example), arrange the <code>plugin/toc-progress/toc-progress.css</code> file accordingly.</p>
		</section>
	</section>
	...
</div>
```

Main section 1 and slide 1 (the title slide) are not in the ToC because they have `data-state="no-toc-progress"`.

The titles for the first column are taken from the `<h2>` elements of the first slide of each main section ("Description", "Installation"...).

The tiles for the second column are taken from the `<h3>` elements of the rest of the slides ("What is Reveal.js-TOC-Progress?", "What does Reveal.js-TOC-Progress do?"... "Necessary files", "CSS"...). In the example, most of the slides have one of these, but those that do not will be shown grouped under the previous element of the second column. For example, slide 8 will be under "Configurable options" together with slide 7. And slides 14 and 15 will be shown under "Customization" together with slide 13.

So, this way you can have as much depth levels and titles as you want, although only the first two will be shown in the ToC, in accordance with the dimensions of reveal.js. I hope you can organize it this way and ToC progress can be of use to you.
